services:
  core:
    image: scafoldr/core
    build:
      context: ./core
    restart: unless-stopped
    
  web:
    image: scafoldr/web
    build:
      context: ./web
    restart: unless-stopped
